In [1]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.models import load_model
import time
!pip install memory_profiler
%load_ext memory_profiler

In [9]:
model=load_model('/home/piyush/Downloads/cancerDetection.h5')

In [50]:
model=load_model('/home/piyush/Downloads/resnet_skin.h5')

In [3]:
import numpy as np
from tensorflow.keras.preprocessing import image
img = image.load_img('/home/piyush/Downloads/Skin cancer ISIC The International Skin Imaging Collaboration/Test/basal cell carcinoma/ISIC_0024411.jpg', target_size=(84,84))
img = image.img_to_array(img)
img=tf.keras.preprsmart_resize(img,(84,84))
img = np.expand_dims(img, axis=0)
model.predict(img)

FileNotFoundError: [Errno 2] No such file or directory: '/home/piyush/Downloads/Skin cancer ISIC The International Skin Imaging Collaboration/Test/basal cell carcinoma/ISIC_0024411.jpg'

In [52]:
import numpy as np
from tensorflow.keras.preprocessing import image
img = image.load_img('/home/piyush/Downloads/cancer dataset/test/benign/1034.jpg', target_size=(180,180))
img = image.img_to_array(img)
img = np.expand_dims(img, axis=0)
#start = time.time()
model.predict(img)
#end = time.time
#print(float(end)-float(start)) # lets say n_frames = 50

array([[0.39289755]], dtype=float32)

In [43]:
%memit
img = image.load_img('/home/piyush/Downloads/cancer dataset/test/benign/1042.jpg', target_size=(180,180))
img = image.img_to_array(img)
img = np.expand_dims(img, axis=0)
model.predict(img)

peak memory: 719.44 MiB, increment: 0.00 MiB


array([[4.96175e-12]], dtype=float32)

In [5]:
img = image.load_img('/home/piyush/Downloads/cancer dataset/test/benign/105.jpg', target_size=(180,180))
img = image.img_to_array(img)
img = np.expand_dims(img, axis=0)
model.predict(img)

array([[0.18298933]], dtype=float32)

In [6]:
img = image.load_img('/home/piyush/Downloads/cancer dataset/test/malignant/1012.jpg', target_size=(180,180))
img = image.img_to_array(img)
img = np.expand_dims(img, axis=0)
model.predict(img) #incorrect

array([[0.00266361]], dtype=float32)

In [7]:
img = image.load_img('/home/piyush/Downloads/cancer dataset/test/malignant/1027.jpg', target_size=(180,180))
img = image.img_to_array(img)
img = np.expand_dims(img, axis=0)
model.predict(img) #incorrect

array([[0.998415]], dtype=float32)

In [8]:
img = image.load_img('/home/piyush/Downloads/cancer dataset/test/malignant/1046.jpg', target_size=(180,180))
img = image.img_to_array(img)
img = np.expand_dims(img, axis=0)
model.predict(img)

array([[0.99579763]], dtype=float32)

In [9]:
img = image.load_img('/home/piyush/Downloads/cancer dataset/test/malignant/1080.jpg', target_size=(180,180))
img = image.img_to_array(img)
img = np.expand_dims(img, axis=0)
model.predict(img)

array([[0.9483665]], dtype=float32)

In [6]:
%%time
import os
c=0
f=0
for i in os.listdir('/home/piyush/Downloads/cancer dataset/test/malignant'):
    try:
        img = image.load_img('/home/piyush/Downloads/cancer dataset/test/malignant/'+str(i), target_size=(224,224))
        img = image.img_to_array(img)
        img = np.expand_dims(img, axis=0) 
        y_pred=model.predict(img)
        f=f+1
        if(y_pred>=0.5):
            c=c+1
    except:
        pass

CPU times: user 31 s, sys: 1.57 s, total: 32.5 s
Wall time: 19.9 s


In [7]:
f

300

In [22]:
c

242

In [24]:
%%time
import os
c=0
print(len(os.listdir('/home/piyush/Downloads/cancer dataset/test/benign')))
for i in os.listdir('/home/piyush/Downloads/cancer dataset/test/benign'):
    try:
        img = image.load_img('/home/piyush/Downloads/cancer dataset/test/benign/'+str(i), target_size=(180,180))
        img = image.img_to_array(img)
        img = np.expand_dims(img, axis=0) 
        y_pred=model.predict(img)
        if(y_pred>=0.5):
            c=c+1
    except:
        pass
print(c)

361
46
CPU times: user 1min 44s, sys: 1.71 s, total: 1min 46s
Wall time: 42.6 s


In [ ]:
print(361-c)

In [15]:
f=((254+249)/(301+361))*100
f

75.98187311178248

In [10]:
f=((237+301)/(301+361))*100
f

81.2688821752266

In [3]:
#*DATA BALANCING*

In [7]:
import shutil
import os
import albumentations as A
import numpy as np
from PIL import Image

In [20]:
transform2=A.Compose([A.HorizontalFlip(p=0.5),])
transform3=A.Compose([A.VerticalFlip(p=0.2),])
transform4=A.Compose([A.RandomBrightnessContrast(p=0.2),])
transform5=A.Compose([A.Rotate(45),])
transform9=A.Compose([A.GaussNoise(var_limit=(10.0, 50.0), always_apply=False, p=0.5),])
transform10=A.Compose([A.Rotate(30),])

In [13]:
os.makedirs('/home/piyush/Downloads/Generate/train/actinic keratosis')
os.makedirs('/home/piyush/Downloads/Generate/train/basal cell carcinoma')
os.makedirs('/home/piyush/Downloads/Generate/train/dermatofibroma')
os.makedirs('/home/piyush/Downloads/Generate/train/melanoma')
os.makedirs('/home/piyush/Downloads/Generate/train/nevus')
os.makedirs('/home/piyush/Downloads/Generate/train/pigmented benign keratosis')
os.makedirs('/home/piyush/Downloads/Generate/train/seborrheic keratosis')
os.makedirs('/home/piyush/Downloads/Generate/train/squamous cell carcinoma')
os.makedirs('/home/piyush/Downloads/Generate/train/vascular lesion')

In [10]:
f=0
for i in os.listdir('/home/piyush/Downloads/Skin cancer ISIC The International Skin Imaging Collaboration/Train/actinic keratosis'):
    try:
        im=Image.open('/home/piyush/Downloads/Skin cancer ISIC The International Skin Imaging Collaboration/Train/actinic keratosis/'+str(i))
        im.save('/home/piyush/Downloads/Generate/train/actinic keratosis/'+i)
        image=np.array(im)
        transformed2 = transform2(image=image)
        transformed_image = transformed2["image"]
        ximage6=Image.fromarray(transformed_image)
        ximage6.save('/home/piyush/Downloads/Generate/train/actinic keratosis/'+str(f)+'.jpg')
        f=f+1
        transformed3 = transform3(image=image)
        transformed_image = transformed3["image"]
        ximage5=Image.fromarray(transformed_image)
        ximage5.save('/home/piyush/Downloads/Generate/train/actinic keratosis/'+str(f)+'.jpg')
        f=f+1
        transformed10 = transform10(image=image)
        transformed_image = transformed10["image"]
        ximage1=Image.fromarray(transformed_image)
        ximage1.save('/home/piyush/Downloads/Generate/train/actinic keratosis/'+str(f)+'.jpg')
        f=f+1
    except :
        pass

In [14]:
f=0
for i in os.listdir('/home/piyush/Downloads/Skin cancer ISIC The International Skin Imaging Collaboration/Train/dermatofibroma'):
    try:
        im=Image.open('/home/piyush/Downloads/Skin cancer ISIC The International Skin Imaging Collaboration/Train/dermatofibroma/'+str(i))
        im.save('/home/piyush/Downloads/Generate/train/dermatofibroma/'+i)
        image=np.array(im)
        transformed2 = transform2(image=image)
        transformed_image = transformed2["image"]
        ximage6=Image.fromarray(transformed_image)
        ximage6.save('/home/piyush/Downloads/Generate/train/dermatofibroma/'+str(f)+'.jpg')
        f=f+1
        transformed3 = transform3(image=image)
        transformed_image = transformed3["image"]
        ximage5=Image.fromarray(transformed_image)
        ximage5.save('/home/piyush/Downloads/Generate/train/dermatofibroma/'+str(f)+'.jpg')
        f=f+1
        transformed10 = transform10(image=image)
        transformed_image = transformed10["image"]
        ximage1=Image.fromarray(transformed_image)
        ximage1.save('/home/piyush/Downloads/Generate/train/dermatofibroma/'+str(f)+'.jpg')
        f=f+1
    except :
        pass

In [18]:
f=0
for i in os.listdir('/home/piyush/Downloads/Skin cancer ISIC The International Skin Imaging Collaboration/Train/pigmented benign keratosis'):
    try:
        im=Image.open('/home/piyush/Downloads/Skin cancer ISIC The International Skin Imaging Collaboration/Train/pigmented benign keratosis/'+str(i))
        im.save('/home/piyush/Downloads/Generate/train/pigmented benign keratosis/'+i)
    except :
        pass

In [21]:
f=0
for i in os.listdir('/home/piyush/Downloads/Skin cancer ISIC The International Skin Imaging Collaboration/Train/seborrheic keratosis'):
    try:
        im=Image.open('/home/piyush/Downloads/Skin cancer ISIC The International Skin Imaging Collaboration/Train/seborrheic keratosis/'+str(i))
        im.save('/home/piyush/Downloads/Generate/train/seborrheic keratosis/'+i)
        image=np.array(im)
        transformed2 = transform2(image=image)
        transformed_image = transformed2["image"]
        ximage6=Image.fromarray(transformed_image)
        ximage6.save('/home/piyush/Downloads/Generate/train/seborrheic keratosis/'+str(f)+'.jpg')
        f=f+1
        transformed3 = transform3(image=image)
        transformed_image = transformed3["image"]
        ximage5=Image.fromarray(transformed_image)
        ximage5.save('/home/piyush/Downloads/Generate/train/seborrheic keratosis/'+str(f)+'.jpg')
        f=f+1
        transformed9 = transform9(image=image)
        transformed_image = transformed9["image"]
        ximage2=Image.fromarray(transformed_image)
        ximage2.save('/home/piyush/Downloads/Generate/train/seborrheic keratosis/'+str(f)+'.jpg')
        f=f+1
        transformed10 = transform10(image=image)
        transformed_image = transformed10["image"]
        ximage1=Image.fromarray(transformed_image)
        ximage1.save('/home/piyush/Downloads/Generate/train/seborrheic keratosis/'+str(f)+'.jpg')
        f=f+1
    except :
        pass

In [25]:
f=0
for i in os.listdir('/home/piyush/Downloads/Skin cancer ISIC The International Skin Imaging Collaboration/Train/squamous cell carcinoma'):
    try:
        im=Image.open('/home/piyush/Downloads/Skin cancer ISIC The International Skin Imaging Collaboration/Train/squamous cell carcinoma/'+str(i))
        im.save('/home/piyush/Downloads/Generate/train/squamous cell carcinoma/'+i)
        image=np.array(im)
        transformed2 = transform2(image=image)
        transformed_image = transformed2["image"]
        ximage6=Image.fromarray(transformed_image)
        ximage6.save('/home/piyush/Downloads/Generate/train/squamous cell carcinoma/'+str(f)+'.jpg')
        f=f+1
    except :
        pass

In [24]:

f=0
for i in os.listdir('/home/piyush/Downloads/Skin cancer ISIC The International Skin Imaging Collaboration/Train/vascular lesion'):
    try:
        im=Image.open('/home/piyush/Downloads/Skin cancer ISIC The International Skin Imaging Collaboration/Train/vascular lesion/'+str(i))
        im.save('/home/piyush/Downloads/Generate/train/vascular lesion/'+i)
        image=np.array(im)
        transformed2 = transform2(image=image)
        transformed_image = transformed2["image"]
        ximage6=Image.fromarray(transformed_image)
        ximage6.save('/home/piyush/Downloads/Generate/train/vascular lesion/'+str(f)+'.jpg')
        f=f+1
        transformed3 = transform3(image=image)
        transformed_image = transformed3["image"]
        ximage5=Image.fromarray(transformed_image)
        ximage5.save('/home/piyush/Downloads/Generate/train/vascular lesion/'+str(f)+'.jpg')
        f=f+1
    except :
        pass

In [26]:
lst=['actinic keratosis','basal cell carcinoma','dermatofibroma','melanoma','nevus','pigmented benign keratosis','seborrheic keratosis','squamous cell carcinoma','vascular lesion']
for i in lst:
    os.makedirs('/home/piyush/Downloads/train/'+str(i))

In [32]:
f=0
for c in lst:
    for i in os.listdir('/home/piyush/Downloads/Generate/train/'+c+'/'):
        if f<=380:
            try:
                shutil.copy2('/home/piyush/Downloads/Generate/train/'+c+'/'+i,'/home/piyush/Downloads/train/'+lst[c]+'/'+i)
            except:
                pass
        f=f+1

In [14]:
model=load_model('/home/piyush/Downloads/Skin cancer ISIC The International Skin Imaging Collaboration/ISIC.h5')

In [9]:
train_data=tf.keras.preprocessing.image_dataset_from_directory('/home/piyush/Downloads/Skin cancer ISIC The International Skin Imaging Collaboration/train',image_size=(112,112),color_mode="rgb",
    batch_size=15,
    shuffle=True,
    seed=123)
test_data=tf.keras.preprocessing.image_dataset_from_directory('/home/piyush/Downloads/Skin cancer ISIC The International Skin Imaging Collaboration/Test',image_size=(112,112),color_mode="rgb",
    batch_size=1,
    shuffle=True,
    seed=123)

Found 3315 files belonging to 9 classes.
Found 122 files belonging to 9 classes.


In [10]:
name=train_data.class_names
name

['actinic keratosis',
 'basal cell carcinoma',
 'dermatofibroma',
 'melanoma',
 'nevus',
 'pigmented benign keratosis',
 'seborrheic keratosis',
 'squamous cell carcinoma',
 'vascular lesion']

In [11]:
import numpy as np
from tensorflow.keras.preprocessing import image
img = image.load_img('/home/piyush/Downloads/Skin cancer ISIC The International Skin Imaging Collaboration/Test/basal cell carcinoma/ISIC_0024432.jpg', target_size=(112,112))
img = image.img_to_array(img)
img = np.expand_dims(img, axis=0)
print(name[np.argmax(model.predict(img))],"with an accuracy of",model.predict(img)[0][np.argmax(model.predict(img))]*100)

squamous cell carcinoma with an accuracy of 44.713109731674194


In [12]:
model.predict(img)

array([[3.1419452e-02, 1.3099721e-01, 2.4680176e-03, 1.3314368e-02,
        3.5268474e-01, 2.0736953e-02, 1.2907479e-04, 4.4713110e-01,
        1.1190030e-03]], dtype=float32)

In [13]:
model.evaluate(test_data)

122/122 [==============================] - 26s 207ms/step - loss: 4.9360 - accuracy: 0.2131


[4.935966491699219, 0.21311475336551666]

In [8]:
import numpy as np
import cv2
import os
x=[]
y=[]
for i in os.listdir('/home/piyush/Downloads/cancer dataset/train/benign/'):
    img=cv2.imread('/home/piyush/Downloads/cancer dataset/train/benign/'+i)
    x.append(img)
    y.append(0)

In [9]:
for i in os.listdir('/home/piyush/Downloads/cancer dataset/train/malignant/'):
    img=cv2.imread('/home/piyush/Downloads/cancer dataset/train/malignant/'+i)
    x.append(img)
    y.append(1)

In [12]:
x=np.asarray(x)/255
x[0]

array([[[0.69411765, 0.65098039, 0.93333333],
        [0.69803922, 0.66666667, 0.94117647],
        [0.69803922, 0.66666667, 0.94117647],
        ...,
        [0.67058824, 0.64705882, 0.90196078],
        [0.66666667, 0.65490196, 0.89803922],
        [0.68627451, 0.65490196, 0.90980392]],

       [[0.70588235, 0.65098039, 0.93333333],
        [0.69803922, 0.65098039, 0.93333333],
        [0.70196078, 0.65490196, 0.9372549 ],
        ...,
        [0.6627451 , 0.63921569, 0.89411765],
        [0.6627451 , 0.65882353, 0.90196078],
        [0.67058824, 0.67058824, 0.92156863]],

       [[0.68627451, 0.65098039, 0.9372549 ],
        [0.6745098 , 0.63921569, 0.9254902 ],
        [0.68627451, 0.64313725, 0.91764706],
        ...,
        [0.65882353, 0.64313725, 0.89803922],
        [0.63921569, 0.64705882, 0.89803922],
        [0.64313725, 0.64313725, 0.89411765]],

       ...,

       [[0.63137255, 0.60784314, 0.88627451],
        [0.65882353, 0.61568627, 0.90196078],
        [0.64705882, 0

In [18]:
tx=[]
ty=[]
for i in os.listdir('/home/piyush/Downloads/cancer dataset/test/benign/'):
    img=cv2.imread('/home/piyush/Downloads/cancer dataset/test/benign/'+i)
    tx.append(img)
    ty.append(0)
for i in os.listdir('/home/piyush/Downloads/cancer dataset/test/malignant/'):
    img=cv2.imread('/home/piyush/Downloads/cancer dataset/test/malignant/'+i)
    tx.append(img)
    ty.append(1)


In [20]:
tx=np.asarray(tx)
tx=tx/255

TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

In [25]:
x=x.flatten()
x[1]

0.6509803921568628

In [23]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=5,weights='distance',p=1,n_jobs=20)
neigh.fit(x,y)

ValueError: Found array with dim 4. Estimator expected <= 2.

In [ ]:
neigh.predict()

In [1]:
import os
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
data=pd.read_csv('/home/piyush/Downloads/archive (2)/HAM10000_metadata.csv')

In [3]:
s=['df','mel','bcc','nv','vasc','akiec','bkl']

In [4]:
for i in s:
  os.makedirs('/home/piyush/Downloads/skin/total/'+i)

In [5]:
import shutil
for i in os.listdir('/home/piyush/Downloads/archive (2)/ham10000_images_part_2'):
  shutil.move('/home/piyush/Downloads/archive (2)/ham10000_images_part_2/'+i,'/home/piyush/Downloads/archive (2)/ham10000_images_part_1/'+i)

In [6]:
for i in s:
  for j in range(0,10015):
    if i==data['dx'][j]:
      shutil.copy('/home/piyush/Downloads/archive (2)/ham10000_images_part_1/'+data['image_id'][j]+'.jpg','/home/piyush/Downloads/skin/total/'+i+'/'+data['image_id'][j]+'.jpg')

In [7]:
for i in s:
  print(len(os.listdir('/home/piyush/Downloads/skin/total/'+i)))

115
1113
514
6705
142
327
1099


In [8]:
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing import image
import cv2
X=[]
y=[]
dic={'df':0,'mel':1,'bcc':2,'nv':3,'vasc':4,'akiec':5,'bkl':6}
for i in s:
  for j in os.listdir('/home/piyush/Downloads/skin/total/'+i):
    img = os.path.join('/home/piyush/Downloads/skin/total/'+i, j)
    img = image.load_img(img, target_size=(84,84),color_mode='rgb')
    img = image.img_to_array(img)
    X.append(img)
    y.append(dic[i])

In [9]:
X=np.asarray(X)/255
y=np.asarray(y)

In [10]:
X.shape

(10015, 84, 84, 3)

In [11]:
X[0]

array([[[0.6901961 , 0.6156863 , 0.6313726 ],
        [0.6901961 , 0.60784316, 0.627451  ],
        [0.7058824 , 0.62352943, 0.6431373 ],
        ...,
        [0.6156863 , 0.5529412 , 0.6039216 ],
        [0.62352943, 0.56078434, 0.6117647 ],
        [0.62352943, 0.54901963, 0.62352943]],

       [[0.67058825, 0.57254905, 0.59607846],
        [0.6666667 , 0.58431375, 0.61960787],
        [0.6901961 , 0.60784316, 0.6431373 ],
        ...,
        [0.62352943, 0.56078434, 0.6117647 ],
        [0.61960787, 0.54901963, 0.6039216 ],
        [0.6039216 , 0.5372549 , 0.6       ]],

       [[0.68235296, 0.5764706 , 0.59607846],
        [0.6862745 , 0.62352943, 0.63529414],
        [0.65882355, 0.5803922 , 0.5882353 ],
        ...,
        [0.627451  , 0.5647059 , 0.6156863 ],
        [0.6039216 , 0.5411765 , 0.5921569 ],
        [0.5921569 , 0.5176471 , 0.5921569 ]],

       ...,

       [[0.59607846, 0.5411765 , 0.60784316],
        [0.59607846, 0.5294118 , 0.5921569 ],
        [0.59607846, 0

In [12]:
from imblearn.over_sampling import ADASYN 

In [13]:
nsamples, nx, ny ,z= X.shape
X= X.reshape((nsamples,nx*ny*z))
sm =ADASYN(random_state=42)
X,y = sm.fit_resample(X, y)

In [14]:
from numpy import save
save('skindata.npy',X)
save('skinlabel.npy',y)

In [27]:
X=np.asarray(X).reshape(-18,84,3)
X.shape

(47012, 112, 112, 3)

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_val,y_train,y_val=train_test_split(X,y,test_size=0.2,random_state=42)

In [1]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.models import load_model

In [12]:
model=load_model('/home/piyush/Downloads/mobile_skin.h5')

In [53]:
import os
c=0
f=0

y_p=[]
y_true=[]

for i in os.listdir('/home/piyush/Downloads/cancer dataset/test/malignant'):
    try:
        #print(i)
        img = image.load_img('/home/piyush/Downloads/cancer dataset/test/malignant/'+str(i), target_size=(180,180))
        img = image.img_to_array(img)
        img = np.expand_dims(img, axis=0) 
        y_pred=model.predict(img)
        #print(y_pred)
        f=f+1
        if(y_pred>=0.5):
            c=c+1
            y_p.append(1)
        else:
            y_p.append(0)
        y_true.append(1)
    except:
        pass

In [54]:
len(y_p)

300

In [55]:
len(y_true)

300

In [56]:
c=0
print(len(os.listdir('/home/piyush/Downloads/cancer dataset/test/benign')))
for i in os.listdir('/home/piyush/Downloads/cancer dataset/test/benign'):
    try:
        img = image.load_img('/home/piyush/Downloads/cancer dataset/test/benign/'+str(i), target_size=(180,180))
        img = image.img_to_array(img)
        img = np.expand_dims(img, axis=0) 
        y_pred=model.predict(img)
        #print(y_pred)
        if(y_pred>=0.5):
            c=c+1
            y_p.append(0)
        else:
            y_p.append(1)
        y_true.append(0)
    except:
        pass
print(c)

361
16


In [57]:
print(len(y_p))
print(len(y_true))

660
660


In [35]:
from sklearn.metrics import f1_score
f1_score(y_p, y_true)
#mobile_skin

0.47783251231527096

In [42]:
#distorted_skin
f1_score(y_p, y_true)

0.639618138424821

In [58]:
#resnet_skin
f1_score(y_p, y_true)

0.43878787878787884

In [1]:
import csv

In [3]:
file = open('/home/piyush/Downloads/archive/GroundTruth.csv')

In [4]:
csvreader = csv.reader(file)

In [5]:
header = []
header = next(csvreader)
header

['image', 'MEL', 'NV', 'BCC', 'AKIEC', 'BKL', 'DF', 'VASC']

In [6]:
rows = []
for row in csvreader:
        rows.append(row)
rows

[['ISIC_0024306', '0.0', '1.0', '0.0', '0.0', '0.0', '0.0', '0.0'],
 ['ISIC_0024307', '0.0', '1.0', '0.0', '0.0', '0.0', '0.0', '0.0'],
 ['ISIC_0024308', '0.0', '1.0', '0.0', '0.0', '0.0', '0.0', '0.0'],
 ['ISIC_0024309', '0.0', '1.0', '0.0', '0.0', '0.0', '0.0', '0.0'],
 ['ISIC_0024310', '1.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0'],
 ['ISIC_0024311', '0.0', '1.0', '0.0', '0.0', '0.0', '0.0', '0.0'],
 ['ISIC_0024312', '0.0', '0.0', '0.0', '0.0', '1.0', '0.0', '0.0'],
 ['ISIC_0024313', '1.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0'],
 ['ISIC_0024314', '0.0', '1.0', '0.0', '0.0', '0.0', '0.0', '0.0'],
 ['ISIC_0024315', '1.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0'],
 ['ISIC_0024316', '0.0', '1.0', '0.0', '0.0', '0.0', '0.0', '0.0'],
 ['ISIC_0024317', '0.0', '1.0', '0.0', '0.0', '0.0', '0.0', '0.0'],
 ['ISIC_0024318', '0.0', '0.0', '0.0', '0.0', '0.0', '1.0', '0.0'],
 ['ISIC_0024319', '0.0', '1.0', '0.0', '0.0', '0.0', '0.0', '0.0'],
 ['ISIC_0024320', '0.0', '1.0', '0.0', '0.0', '0

In [12]:
name_dict={}
for i in rows:
    name_dict[i[0]]=header[i.index('1.0')]

In [14]:
len(name_dict.items())

10015

In [15]:
import os
i=1
for i in range(1,8):
    os.makedirs('/home/piyush/Downloads/archive/train'+header[i])
    os.makedirs('/home/piyush/Downloads/archive/test'+header[i])

In [21]:
import shutil
for i in name_dict.keys():
    shutil.copy('/home/piyush/Downloads/archive/images/'+i+'.jpg','/home/piyush/Downloads/archive/train/'+name_dict[i])

In [25]:
total_images=0
for j in set(name_dict.values()):
    print(len(os.listdir('/home/piyush/Downloads/archive/train/'+j)))
    total_images=total_images+len(os.listdir('/home/piyush/Downloads/archive/train/'+j))

1099
327
514
142
1113
115
6705


In [26]:
total_images

10015